### ISSUE TITLE
[4.1.4] Serializable

### ISSUE THREAD

**Issue by jennkimm** [jennkimm/Kotlin-Study#10]
### 직렬화가 왜 필요한가?
- 생성한 객체를 파일로 저장해야 할 경우
- 저장한 객체를 읽을 일이 생길 수도 있음
- 다른 서버에서 생성한 객체를 받을 일도 생길 수 있음

즉, 자바 직렬화 형태의 데이터 교환은 자바 시스템 간 데이터를 교환하기 위해서 존재한다.

### 자바 직렬화의 장점?
자바 시스템에서 개발에 최적화.
복잡한 데이터 구조의 클래스 객체라도 직렬화 기본 조건만 지키면 큰 작업 없이 바로 직렬화 가능.

### 자바 직렬화 기본 조건?
자바 기본 타입과 `java.io.Serializable` 인터페이스 상속받는 객체.
``` .java
public interface Serializable {

}
```
### 직렬화란?
- 자바 시스템 내부에서 사용되는 객체 또는 데이터를 외부의 자바 시스템에서도 사용할 수 있도록 바이트 형태로 데이터를 변환하는 기술과 바이트로 변환된 데이터를 다시 객체로 변환하는 기술(역직렬화)를 아울러서 말한다.
- 시스템적으로 이야기하자면 JVM(Java Virtual Machine 이하 JVM)의 메모리에 상주(힙 또는 스택)되어 있는 객체 데이터를 바이트 형태로 변환하는 기술과 직렬화된 바이트 형태의 데이터를 객체로 변환해서 JVM으로 상주시키는 형태를 같이 이야기한다.

 [출처](https://techblog.woowahan.com/2550/)

**Comment by rosesua318** [comment]
정리 감사합니다 👍 👍  때마침 오늘 코드 짜면서 프래그먼트 간 데이터 전달 시에 객체 데이터를 전달할 때 Serializable을 이용했어요. ㅎㅎ

**Comment by jennkimm** [comment]
> 정리 감사합니다 👍 👍 때마침 오늘 코드 짜면서 프래그먼트 간 데이터 전달 시에 객체 데이터를 전달할 때 Serializable을 이용했어요. ㅎㅎ

크으으으👍
