### ISSUE TITLE
[4.3.3] by 키워드로 클래스 위임

### ISSUE THREAD

**Issue by jennkimm** [jennkimm/Kotlin-Study#12]
p181 에 내부 컨테이너가 addAll을 처리할 때 루프를 돌면서 add를 호출할 수도 있지만, 최적화를 위해 다른 방식을 택할 수도 있다고 했는데, 여기서 '루프를 돈다'는게 어떤 의미인지 잘 모르겠어요. 그리고 addAll을 처리할 때 어떻게 add가 호출될 수 있는지..? 그리고 최적화를 위해 택해지는 다른 방식에는 무엇이 있는건지..? 이 문장 자체가 앞뒤문맥을 살펴봐도 잘 와닿지가 않네요..

**Comment by rosesua318** [comment]
p181에서 내부 컨테이너는 innerSet으로 add와 addAll 모두 리턴할 때 innerSet을 이용합니다. innerSet은 MutableCollection의 구현을 위임 받고 있는 객체입니다. 따라서 add와 addAll의 리턴문에서 innerSet이 호출한 add와 addAll이 어떻게 구현되어 있는지는 여기선 알 수 없습니다. 사용자는 그저 MutableCollection에 문서화된 API인 add나 addAll을 활용하는 것이기 때문입니다. 그렇기 때문에, innerSet이 addAll을 처리할 때 루프를 돌면서, 즉 for문이든 while문이든 반복문을 이용하여 add를 원하는 만큼 호출하여 addAll을 처리할 수도 있고, 루프를 도는 자체가 메모리에 부담이 될 수 있기 때문에 최적화를 위해 재귀를 이용한다든지 그밖에 다른 알고리즘을 이용한다든지는 내부 클래스인 MutableCollection에서 addAll을 어떻게 구현하느냐에 따라 다르겠죠. 이렇게 구현 방식에 대한 의존관계가 생기지 않기 때문에,  MutableCollection이 문서화된 API를 변경하지 않는 한 CountingSet 코드가 잘 작동할 것입니다.

**Comment by jennkimm** [comment]
아..! 'innerSet의' add, addAll을 반환하고 있다니...! 코드를 꼼꼼히 봐야겠군요..ㅎㅎ 그래서 MutableCollection 의 구현에 의존하지 않으니, CountingSet의 add, addAll은 마음대로 구현할 수 있다는 거군요. 
+) 실제 addAll 이 어떻게 구현되어 있는지 찾아봤는데, 내부적으로는 자바에서 구현된 컬렉션을 복사하는 함수를 사용하고 있는것 같습니다
List 의 addAll 구현을 보면, 인자로 받은 컬렉션을 array로 바꿔서 `System.arraycopy` 로 `array`에 복사를 해놓고, while문을 돌면서 원소를 `array`에 추가합니다.

**Comment by rosesua318** [comment]
오 자세한 구현이 어떻게 되어있는지 몰랐는데, 감사해요! 실제로는 while문을 돌면서 원소를 추가하는 형태군요 👍
