### ISSUE TITLE
[5.3.1 시퀀스 연산 실행] 최종 연산 질문

### ISSUE THREAD

**Issue by rosesua318** [jennkimm/Kotlin-Study#14]
이 챕터에서는 최종 연산이 없으면 지연 계산 방식으로 인해서 코드를 실행해도 아무런 내용이 출력되지 않는다고 예제를 통해 되어있습니다. 최종 연산을 호출하면 연기 됐던 모든 계산이 수행 된다고 p225에 설명되어 있습니다. 그런데, p226 위쪽의
```kotlin
println(listOf(1, 2, 3, 4).asSequence().map { it * it }.find { it > 3 })
```
에서는 .toList()와 같은 최종 연산이 없는데 왜 정상적으로 출력이 되는 걸까요? 가장 바깥에 println()으로 둘러싼 경우 최종 연산의 유무와는 상관 없이 출력이 되는 걸까요? 책을 읽어보아도 이해가 되지 않아 남겨 봅니다!

**Comment by jennkimm** [comment]
앗 여기서는 `find`가 최종 연산인거 같아요! 최종 연산을 통해 얻는 결과는, 시퀀스로부터 일련의 계산을 수행해 얻을 수 있는 컬렉션이나 원소, 숫자 또는 객체라고 나와있는데, 이 중 하나로 만들어줄 수 있는 연산을 최종 연산이라고 하는 것 같습니다. 위에 예제의 결과도 이 중 하나인 숫자(4) 이구요. `toList()`, `toInt()` 외에도` sum()`,` any()`, `find()` 등이 될 수 있겠네요!

**Comment by rosesua318** [comment]
아하 최종 연산의 개념을 잘못 이해하고 있었어요. 무조
건 컬렉션으로 만들어줘야 한다고 예제들 보고 판단했어요.! 자세한 설명 감사드려요☺️
