### ISSUE TITLE
[6.3.4] 플랫폼 타입

### ISSUE THREAD

**Issue by rosesua318** [jennkimm/Kotlin-Study#16]
## 플랫폼 타입이란?
Java에서 참조된 모든 내용은 null일 수 있으며,  이로 인해 Kotlin의 엄격한 null-safety 요구는 Java에서 오는 객체에 대해 비실용적입니다. 그렇기 때문에, Java 타입들의 선언은 Kotlin에서 특정 방식으로 처리되며 이를 플랫폼 타입이라고 합니다.
=> 코틀린이 널 관련 정보를 알 수 없는 타입
+ @Nullable과 @Notnull이 붙지 않은 Java에서 온 참조형은 모두 플랫폼 타입으로 처리

## 표현 방법
T! 라고 표현 ex) String!, View!
변수의 선언 등에는 사용할 수 x
```java
public class Example {
    public static String getStringJava() {
         return null;
    }
}
```
```kotlin
val str: String! = Example.getStringJava() // 컴파일 에러
```
올바른 변수 선언 후 대입 방법
```kotlin
val str = Example.getStringJava() // str은 String! 타입
val nullableStr: String? = str // String? 타입
val notNullStr: String = str // String 타입
```

## Java 타입을 Nullable or NotNull로 지정
Java로 정의된 메소드를 Kotlin에서 호출할 경우, 의도치 않아도 NullPointerException이나 IllegalStateException이 발생할 수 있습니다. 따라서, Java로 정의된 메소드에 @Nullable이나 @NotNull 어노테이션을 붙이는 것이 좋다고 하네요. 예로 들면,
```java
public class Example {
    @Nullable
    public static String getStringJavaWithNullableAnnotation() {
        return null;
    }
}
```
```kotlin
val str = Example.getStringJavaWithNullableAnnotaion() 
println(str?.length)
```
이런 식으로 말이죠. 공부하면서 이해한 부분 같이 보면 좋을 것 같아서 남겨봅니다 😄 

[출처-코틀린 공식문서](https://kotlinlang.org/docs/java-interop.html#notation-for-platform-types)
[출처](https://pluu.github.io/blog/kotlin/2017/02/26/kotlin-null/)

**Comment by jennkimm** [comment]
정리 감사합니다!👍

직접 자바로 API를 정의하고 이를 코틀린에서 사용하는 경우보다, 코틀린으로 작성하고 있는데 이미 정의되어있는 자바 라이브러리 함수들을 가져와 사용할 일들이 훨씬 많을거기 때문에, 우리는 예상치 못한 예외 발생을 최소화 하기 위해 자바 문서를 잘 살펴보고 어떤 식으로 정의가 되어있는지 확인하고 갖다가 쓰도록 연습하는게 좋겠네요~!

---
### 발생할 수 있는 예외에 대한 정리

- `NullPointerException`

널인 값의 멤버에 . 으로 접근하려고 할 때
``` kotlin
public class Utility {
    public static String returnStringJava() {
        return null;
    }
}
val str = Utility.returnStringJava()
println(str.length) // 이 시점에 NullPointerException
```

- `IllegalStateException`

널이 될 수 없는 타입에 널을 대입
``` kotlin
public class Utility {
    public static String returnStringJava() {
        return null;
    }
}
val str: String = Utility.returnStringJava() // IllegalStateException
```

- `IllegalArgumentException`

수신 객체가 널일 경우 발생
``` kotlin
fun yellAt(person: Person) {
    println(person.name.toUpperCase() + "!!!") // illegalArgumentException
}
yellAt(Person(null))
```

* 참고
`NullPointerException`은 어떤 null 인 값(의도된) 으로 _실행 도중_ 부적절하게 사용되었을때 발생하는 예외이고,
(원문 : Notice that all of them are thrown by the runtime when null is used inappropriately. )
`IllegalArgumentException`은 어떠한 메서드가 수신 객체로 부적절한 값을 받았을 경우 던지는 예외이다.
(원문 : Thrown to indicate that a method has been passed an illegal or inappropriate argument. )
[참고!
](https://stackoverflow.com/questions/3881/illegalargumentexception-or-nullpointerexception-for-a-null-parameter)

**Comment by rosesua318** [comment]
예외 상황들을 예시로 들어주셔서 더 쉽게 이해가 되네요! 정리 감사합니다 ❤️
