### ISSUE TITLE
[2.1.3 변수] 변수 타입 위치

### ISSUE THREAD

**Issue by rosesua318** [jennkimm/Kotlin-Study#2]
64p에 '타입으로 변수 선언을 시작하면 타입을 생략할 경우 식과 변수 선언을 구별할 수 없다.' 라고 되어 있는데 타입을 생략하여도 val, var에 의해서 식과 구분할 수 있지 않나요? 구분이 되지 않는 경우에서 식과 변수 선언이 어떻게 구분이 되지 않는 것인지 예시가 궁금해요.

**Comment by jennkimm** [comment]
말씀해주신 부분은 자바일 경우를 이야기하고 있는 것 같습니다! 코틀린 에서는 이런 이유에서 val, var 이라는 키워드로 변수 선언을 하기 때문에, 타입 생략을 허용한다고 되어있네요:)

**Comment by rosesua318** [comment]
아하 이해되었습니다. 감사해요:)
