### ISSUE TITLE
[8.1.4] append

### ISSUE THREAD

**Issue by jennkimm** [jennkimm/Kotlin-Study#20]
'각 원소를 문자열로 변환하는 방법'을 제어하고 싶어서,
(전) 객체 -> 문자열
``` kotlin
result.append(element)
```
(후) 원소 -> 문자열
``` kotlin
result.append(transform(element)) // transform: (T) -> String = { it.toString() }
```
이런식으로 바꾸면서, `toString()`으로 충분할 수도 있지만, _그렇지 않은 경우도 있다_ 고 하는데.. 
어짜피 `append()` 도 객체를 받아서 toString() 호출해주는데, 굳이 이렇게 원소를 문자열로 바꾸는 방법을 람다로 전달하는 이유가 있을까요?? 이렇게 변경해주었을 때의 장점이 무언인지 딱히 와닿지가 않네요..🤔  (transform 인자를 통해 각 원소에 다양한 람다식을 적용할 수 있다는 것 외에는)

**Comment by rosesua318** [comment]
책을 천천히 다시 읽어보니, 제가 이해한 바로는 `toString()` 외에 뒷페이지에 예시로 나와있듯이 `toLowerCase()` 나 `toUpperCase()`등도 함께 적용하고 싶을 때를 _그렇지 않은 경우도 있다_ 라고 표현한 것 같아요. 서현님이 괄호에서 말씀하신 대로 그런 경우의 장점을 활용하기 위해 `append()`에 함수 타입 파라미터인 `transform`을 이용했다고 이해했습니다! 결론적으로 transform을 이용하면 `toString()`과 함께 transform인자인 다른 람다식도 실행될 수 있기 때문에 사용자가 필요한 경우에 이렇게 사용하면 될 것 같아요.
