### ISSUE TITLE
[9.1.4] 타입 파라미터를 널이 될 수 없는 타입으로 한정

### ISSUE THREAD

**Issue by rosesua318** [jennkimm/Kotlin-Study#22]
책을 읽다보니, 제가 제대로 이해를 한건지 정확하게 하고 넘어가고 싶은 부분이 있어서 이슈 남깁니다!
394p에 보면 _리스트 9.3의 `Comparable<T>`타입도 그런 예다._ 라는 문장이 있는데 
앞 부분에서는 <T: Any>라는 제약이 T 타입이 항상 널이 될 수 없는 타입이 되게 보장한다고 했었는데,
그렇다면 `Comparable<T>` 타입도 그러한 예시라는 것은 리스트 9.3에서 `Comparable<T>?` 형태가 아니기
때문에 이 제약이 널이 될 수 없는 타입이 되게 보장하는 예시 중에 하나라는 뜻이 맞을까요?
아니면 `Comparable<T>`가 특별한 기능이 있기 때문에 그런건지 궁금합니다

**Comment by jennkimm** [comment]
`Comparable<T>?` 가 아니라 `Comparable<T>` 이기 때문인 것 같습니다
`Comparable` 은 비교 가능한 타입 클래스에서 구현하도록 해서 같은 타입끼리의 비교가능한 `compareTo` 메서드를 제공하게끔 하는 인터페이스 같습니다! Boolean, Int, Char, Double 등등에서 상속받아 구현하고 있네요~! [참고](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-comparable/)
