### ISSUE TITLE
[9.1.2] 제네릭 클래스 선언

### ISSUE THREAD

**Issue by jennkimm** [jennkimm/Kotlin-Study#24]
아래 부분 헷갈리네요..

제네릭 클래스를 확장하는 클래스 -> 기반 타입의 제네릭 파라미터에 대해 타입 인자를 지정해야 한다. 이때,
타입 파라미터로 받은 타입을 넘길 수도 있다.
``` kotlin
class ArrayList<T>: List<T> {
    override fun get(index: Int): T = ...
}
```
여기서 ArrayList<T>의 T와 List<T>의 T가 다른거라고 하는데, 그냥 전혀 상관이 없는게 되나요? 아래 `get` 함수의 반환 타입은 ArrayList<T>의 T 타입을 따라가는 걸까요? 근데 주석에 ArrayList의 제네릭 타입 파라미터 T를 List의 타입인자로 넘긴다고 되어있는데, 그러면 결국 ArrayList<T> 의 T 타입을 List<T> 의 T 로 넘긴다는 의미 아닌가요? 그러면 결국 같은 타입파라미터가 되는거 아닌지..

**Comment by rosesua318** [comment]
서현님이 말씀하신 예제 코드에서의 ArrayList의 T 타입과 List의 T 타입은 결론적으로 같은 뜻입니다. 
가령 
```kotlin
class ArrayList<A> : List<T> { 
    override fun get(index: Int) : A = this[index]
}
```
이런 식으로 서현님이 이해하신대로 T가 서로 다른 것이라고 가정하여 코드를 바꿔보면 컴파일 오류가 나는 것을 볼 수 있습니다.
389p 에서 `여기서 ArrayList<T>의 T와 앞에서 본 List<T>의 T는 같지 않다` 라는 문장의 뜻은 388p의 
```kotlin
interface List<T> {
    operator fun get(index: Int) : T
    // ...
}
```
이 예제 코드에서의 List<T>를 지칭하는 것으로 보입니다. 그렇기 때문에 다시 돌아가서 389p 에서 
`ArrayList<T>의 T는 앞에서 본 List<T>의 T와 전혀 다른 타입 파라미터며, 실제로는 T가 아니라 다른 이름을 사용해도 의미에는 아무 차이가 없다` 라고 표현할 수 있게 되는 것 같습니다.
실제로, 
```kotlin
class ArrayList<A> : List<A> { 
    override fun get(index: Int) : A = this[index]
}
```
코드에서 T를 A로 바꾸어도 정상적으로 동작하는 것을 알 수 있습니다. 즉, class ArrayList<T>에서는 확장한 List<T>와 같은 타입 파라미터가 맞으나, 388p에서 정의한 List<T>와는 다르다는 뜻으로 해석하면 될것 같습니다.
