### ISSUE TITLE
[9.2.4] 실체화한 타입 파라미터의 제약

### ISSUE THREAD

**Issue by jennkimm** [jennkimm/Kotlin-Study#25]
실체화한 타입 파라미터는 다음과 같은 일은 할 수 없다.

- 타입 파라미터 클래스의 인스턴스 생성
- 타입 파라미터 클래스의 동반 객체 메소드 호출
위 두 일을 할 수 없는 이유가 궁금합니다. 정확히 '타입 파라미터 클래스'란 무엇인지가 헷갈려서 이유가 감이 안잡히네요ㅜ 
유추하기로는, 타입 파라미터'의' 클래스 인것같기는 한데... 만약 그렇다면 번역이...ㅋㅋ 하.. 
타입 파라미터의 클래스라고 하면, 타입 소거때문에 인스턴스의 생성은 당연히 안되겠네요.. 근데 또 동반 객체 메소드 호출은 인스턴스 생성 자체가 안되니까 따라서 안되겠네요.. 흠...

**Comment by rosesua318** [comment]
저도 이 부분이 이상하다고 생각이 되어서, 표시를 해놓았었는데, 제가 유추하고 넘어간 바로도 타임파라미터'의' 클래스라고 생각하였습니다. 아무래도 번역 문제인 것 같네요.. 
그렇게 해석했을 때, 두 가지 모두 될 수 없는 일이 맞으므로 성립이 되는데,
'타입 파라미터 클래스'라고 하면 책에도 나와있지 않고 자료를 찾아봐도 '타입 파라미터 클래스'라는 것은 존재하지 않는 것 같습니다..
