### ISSUE TITLE
[10.1.1] @Deprecated  애노테이션

### ISSUE THREAD

**Issue by rosesua318** [jennkimm/Kotlin-Study#27]
책을 읽다 보니 433p에 @Deprecated 애노테이션을 사용하는 예제가 있는데.. 두번째 인자로 인해  remove 함수를 호출하는 코드가 있을 때 자동으로 그 코드를 새로운 API 버전에 맞는 코드로 바꿔준다고 하였는데,  새로운 API 버전에 맞는 코드가 여기서는 removeAt(index)인 것인가요? 아니면 버전이 업데이트 될 때마다 자동으로 맞는 코드를 갱신해주는 건지 아니면 대체할 패턴을 사용자가 지정해주는 대로만 적용이 되는 것인지 궁금합니다.
만약 사용자가 지정해주는 대로만 대체가 되는 것이라면 그냥 remove 함수를 removeAt으로 바꾸면 되는 거 아닌가요..?
제가 잘못 이해하고 있는건지 모르겠네요..

**Comment by jennkimm** [comment]
API 를 만드는 입장에서 생각해보면 이해될 것 같아요!
우리가 Android 관련 API를 사용할 때도 어떤 함수를 썼을 때 deprecated 됐다, 대신 이걸 써라! 라고 경고해주는 경우가 종종 있듯, 
@Deprecated 가 붙은 remove 함수를 썼을때 사용자에게 이거 deprecated 됐어, removeAt 을 써! 라고 표시해주고 싶을 때, 사용하는 듯 합니다

**Comment by rosesua318** [comment]
아 관점을 바꿔서 제가 API를 만드는 입장이라고 생각해보면 해결되는 부분이군요..!! 이해 됐습니다 감사해요 👍
