### ISSUE TITLE
[2.5] 코틀린 예외처리

### ISSUE THREAD

**Issue by jennkimm** [jennkimm/Kotlin-Study#3]
예외에는 체크 예외와 언체크 예외로 나뉘는데, 이는 각각 어떤 차이점이 있고, 어떻게 처리하는지 예시 코드와 함께 설명 해주세요

**Comment by rosesua318** [comment]
둘의 명확한 차이점은 체크 예외는 반드시 예외 처리가 필요하나, 언체크 예외는 예외 처리를 해주지 않아도 된다는 점입니다. 사용할 메소드가 체크 예외를 던진다면 이를 catch문으로 잡거나, throws를 정의해서 메소드 밖으로 던져야 합니다. 체크 예외는 컴파일 단계에서 확인을 하는 체크 예외와는 달리 실행 단계에서 확인을 하기 때문에 런타임 예외라고 부르기도 하며, 별도로 catch문으로 잡거나 throws로 선언해주지 않아도 됩니다. 즉, 프로그램에 오류가 있을 때 발생하도록 하는 것이죠. 
throws는 예외를 넘기고 try-catch는 예외를 처리합니다. throws는 예외 발생 이후의 코드는 실행하지 않고, try-catch는 예외 발생 이후의 코드도 실행을 합니다.
코틀린은 체크 예외와 언체크 예외를 구별하지 않기 때문에 자바 코드로 예시를 들어보면
`
class ErrorExample {
    void throwArithmeticException() {
            throw new ArithmeticException();
    }
    void throwIOException() {
            try   {
                   throw new IOException();
            } catch (IOException e) {
                   e.printStackTrace();
            }
    }
    void throwIOException2() throws IOException {
            throw new IOException();
    }
}

public class Example {
    public static void main(String[] args) {
               ErrorExample e1 = new ErrorExample();
               e1.throwArithmeticException();
               e1.throwIOException2();
    }
}
`
이 코드를 보시면 IOException의 경우 체크 예외이므로, 예외를 던질 때 try-catch문으로 처리해주거나(throwIOException1()의 경우), throws로 선언(throwIOException2()의 경우)해주는 것을 알 수 있습니다. 반면에 ArithmeticException은 언체크 예외이므로, try-catch문으로 처리해주거나 throws로 선언해주지 않고 throw로 예외를 던질 수 있습니다.

**Comment by rosesua318** [comment]
둘의 명확한 차이점은 체크 예외는 반드시 예외 처리가 필요하나, 언체크 예외는 예외 처리를 해주지 않아도 된다는 점입니다. 사용할 메소드가 체크 예외를 던진다면 이를 catch문으로 잡거나, throws를 정의해서 메소드 밖으로 던져야 합니다. 체크 예외는 컴파일 단계에서 확인을 하는 체크 예외와는 달리 실행 단계에서 확인을 하기 때문에 런타임 예외라고 부르기도 하며, 별도로 catch문으로 잡거나 throws로 선언해주지 않아도 됩니다. 즉, 프로그램에 오류가 있을 때 발생하도록 하는 것이죠.
throws는 예외를 넘기고 try-catch는 예외를 처리합니다. throws는 예외 발생 이후의 코드는 실행하지 않고, try-catch는 예외 발생 이후의 코드도 실행을 합니다.
코틀린은 체크 예외와 언체크 예외를 구별하지 않기 때문에 자바 코드로 예시를 들어보면
```
class ErrorExample {
    void throwArithmeticException() {
            throw new ArithmeticException();
    }
    void throwIOException() {
           try {
                throw new IOException();
            } catch (IOException e) {
                e.printStackTrace();
            }
    }
    void throwIOException2() throws IOException {
            throw new IOException();
    }
}

public class Example {
    public static void main(String[] args) {
              ErrorExample e1 = new ErrorExample();
              e1.throwArithmeticException();
              e1.throwIOException2();
    }
}
```
이 코드를 보시면 IOException의 경우 체크 예외이므로, 예외를 던질 때 try-catch문으로 처리해주거나(throwIOException1()의 경우), throws로 선언(throwIOException2()의 경우)해주는 것을 알 수 있습니다. 반면에 ArithmeticException은 언체크 예외이므로, try-catch문으로 처리해주거나 throws로 선언해주지 않고 throw로 예외를 던질 수 있습니다.

**Comment by jennkimm** [comment]
조오금 수정할 부분+궁금한 부분이 있어서 인용하겠습니다!ㅎㅎ

> **_언체크 예외_** 는 컴파일 단계에서 확인을 하는 체크 예외와는 달리 실행 단계에서 확인을 하기 때문에 런타임 예외라고 부르기도 하며, 별도로 catch문으로 잡거나 throws로 선언해주지 않아도 됩니다.

체크 예외 -> 언체크 예외

> throws는 예외를 넘기고 try-catch는 예외를 처리합니다. throws는 예외 발생 이후의 코드는 실행하지 않고, **_try-catch는 예외 발생 이후의 코드도 실행을 합니다._**

이 부분은 설명이 조금 애매한것(?) 같은데, try에 예외 발생 가능성이 있는 코드를 넣고, 예외가 발생한다면 catch 문으로 가고, 만약 catch에서 return 을 하면 함수가 반환되는거고(끝) 아니면 finally 문도 실행되는 그런 구문이라고 정리하는게 어떨까요?

> class ErrorExample {

에러(error)와 예외(exception)는 다른 개념이므로 클래스 네이밍을 변경하면 좋을것 같네요!

>     void throwIOException() {
아래의 설명에 의하면 요 함수도 `throwIOException1` 으로 바꾸거나 or 아래 설명을 바꾸거나 해야겠네요
>            try {
>                 throw new IOException();
>             } catch (IOException e) {
>                 e.printStackTrace();
>             }
>     }
>     void throwIOException2() throws IOException {
>             throw new IOException();
>     }
> }
> 
> public class Example {
>     public static void main(String[] args) {
>               ErrorExample e1 = new ErrorExample();
>               e1.throwArithmeticException();
>               e1.throwIOException2();
>     }
> }
> ```
> 
그리고 해당 예제 코드는 컴파일이 안됩니다..! `throwIOException2` 함수는 예외를 던지는데 받는 쪽에서 아무런 처리가 없네요. 예외를 발생시킬 수 있는 함수를 호출할땐 어떻게 한다?ㅎㅎ try/catch 문으로 감싸거나 `main` 에서 rethrow 하거나! 해야겠네요~!

**Comment by rosesua318** [comment]
인용해주신 부분들 참고한 뒤에 다시 개념 공부하고 정리합니다 ㅎㅎ

둘의 명확한 차이점은 체크 예외는 예외 처리를 하지 않으면 컴파일이 되지 않지만, 언체크 예외는 예외 처리를 해주지 않아도 컴파일이 된다는 점입니다. 즉, 체크 예외가 발생하면 try-catch문을 통해 처리해 주거나, throws를 정의해서 메소드 밖으로 던져야 합니다. 언체크 예외는 컴파일 단계에서 확인을 하는 체크 예외와는 달리 실행 단계에서 확인을 하기 때문에 런타임 예외라고 부르기도 하며, RuntimeException을 상속 받습니다. 그렇기 때문에, try-catch문이나 throws를 통해 조치를 취하지 않아도 컴파일이 됩니다. 
throws는 예외를 넘기고 try-catch는 예외를 처리합니다. throws는 예외 발생 이후의 코드를 실행하지 않습니다. try-catch문은 try문에는 예외가 발생할 수 있는 코드를 넣고, 예외가 발생하는 경우 catch문으로 가게 됩니다. catch문에 return이 있다면 함수가 반환되어 끝나게 되지만, 그렇지 않은 경우 finally 문도 실행되고, finally 문이 없는 경우에도 try-catch문 다음 줄에 해당하는 코드가 실행 됩니다. 
코틀린은 체크 예외와 언체크 예외를 구분하지 않기 때문에 자바 코드로 예시를 들어보겠습니다.

```
import java.io.IOException;

class ExceptionClass {
    void throwArithmeticException() {
        throw new ArithmeticException();
    }
    void throwIOException1() {
        try {
            throw new IOException();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    void throwIOException2() throws IOException {
        throw new IOException();
    }
}

public class ExceptionExample {
    public static void main(String[] args) {
        ExceptionClass e1 = new ExceptionClass();
        // 1) 언체크 예외 ArithmeticException 테스트
        e1.throwArithmeticException();
        
        // 2) 체크 예외 IOException을 try-catch문으로 처리해주기
        e1.throwIOException1();

        // 3) 체크 예외 IOException을 throws로 처리해주기
        try {
            e1.throwIOException2();
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        // 만약 1)번을 테스트 하고 싶다면 2) 3) 부분은 주석 처리 후 테스트 해주세요.
    }
}
```

해당 코드를 보시면 IOException의 경우 체크 예외이므로, 예외를 던질 때 try-catch문으로 처리해주거나(throwIOException1()의 경우), throws로 선언(throwIOException2()의 경우) 해서 처리해주는 것을 알 수 있습니다. 
반면에 ArithmeticException은 언체크 예외이므로, try-catch문으로 처리해주거나 throws로 선언하여 처리해주지 않고 throw로 예외를 던져도 컴파일 되어 실행이 됩니다.
