### ISSUE TITLE
[3.2.1 이름 붙인 인자]  불리언 플래그

### ISSUE THREAD

**Issue by rosesua318** [jennkimm/Kotlin-Study#5]
인자에 이름을 붙이지 않고 함수에 전달할 경우 함수 호출 코드가 모호해지는 문제점이 생긴다고 하였는데, 특히 불리언 플래그 값을 전달해야 하는 경우 흔히 발생한다고 되어있습니다.
왜 불리언 플래그 값을 전달할 때 흔하게 발생한다는 건지 궁금합니다. 예를 들어서 설명 해주시면 감사하겠습니다.ㅎㅎ
제가 유추했을 때는 인자가 불리언 플래그 값으로만 이루어진 함수의 경우
example(true, false, true, false); 이런 식으로 되어있어서 함수 시그니처를 잘 알지 못하는 경우 무엇을 뜻하는지 알기 쉽기 어렵고, 다른 타입에 비해 가능한 값이 2가지 뿐이라 더 모호하다고 생각하였는데 맞을까요?

**Comment by jennkimm** [comment]
우선 제가 생각했을때, 함수의 인수로 boolean 타입을 갖는다는 것은, 해당 함수가 최소 두 가지 일을 수행할 수 있다는 것이기에, 되도록이면 지양해야 한다고 생각합니다. 

다른 타입에 비해서 불리언 플래그 값을 전달할 경우에 특히 모호해지는지는.. 글쎄요 저도 정확한 이유는 잘 모르겠어요. 유추하신 이유가 어느정도 맞지 않을까 생각해봅니다..ㅎㅎ  Kotlin 에서는 자바의 함수에 인수가 많거나 호출 시 인자의 역할이 불분명한 경우를 보완하여 나온 것이 `named parameter` 라고 알아두면 되지 않을까 싶어요ㅎㅎ

그리고 이를 보완하는 방식도 개인 스타일에 따라서도 다를것 같다고 생각합니다. 개인적으로는 플래그값일 경우 가능하면 `enum` 타입을 사용해서 넘겨줄 것 같아요. (이 외에도 주석 사용하기, 인자에 이름 붙이기 등이 소개되어 있네요.)

**Comment by rosesua318** [comment]
named parameter 개념을 정확하게 알면 되겠군요. 세 가지 방법 중에서 상황에 따라 알맞게 쓰면 되겠네요! 감사합니다 ㅎㅎ
