### ISSUE TITLE
[3.3] 확장 함수는 오버라이드할 수 없다

### ISSUE THREAD

**Issue by jennkimm** [jennkimm/Kotlin-Study#7]
코틀린의 일반 메소드는 오버라이드가 가능하지만, 확장 함수는 오버라이드할 수 없는 이유를  호출될 함수 타입 결정 방식에 따라 정리해보면 좋을 것 같아요~

**Comment by rosesua318** [comment]
상위 클래스의 함수를 하위 클래스에서 오버라이드한 경우에는, 실행 시점에 객체 타입에 따라 호출될 대상 메소드를 결정하는 방식인 동적 디스패치 방식이기 때문에, 상위 타입 변수에 하위 타입 변수를 대입했을 경우 해당 변수가 가리키는 객체의 실제 타입인 하위 타입의 오버라이드된 메소드가 호출 됩니다. 
다음으로, 확장 함수는 클래스 밖에 선언되어 있음에도 불구하고 어떤 클래스의 멤버 메소드인 것처럼 호출할 수 있기 때문에 동일하게 동적 디스패치 방식이 적용될 것 같지만 확장 함수는 컴파일 시점에 호출될 확장 함수를 정적으로 결정하는 방식으로, 정적 메소드와 같은 특징을 가지고 있기 때문에 오버라이드 할 수 없습니다. 예로 들어, 함수 이름과 파라미터가 완전히 같은 확장 함수를 상위 클래스와 하위 클래스에서 정의해도 일반 메소드처럼 객체의 동적인 타입에 의해 확장 함수가 결정되지 않습니다. 즉, 상위 타입 변수에 하위 타입 변수를 대입했을 경우 해당 변수가 확장함수를 호출했을 때, 해당 변수가 가리키는 객체의 실제 타입은 하위 타입이지만, 수신객체 타입이 상위 타입이므로 상위 타입에서 정의한 확장 함수가 호출 됩니다.
