### ISSUE TITLE
[4.1.3 가시성 변경자] 자바의 모듈 내부 가시성

### ISSUE THREAD

**Issue by rosesua318** [jennkimm/Kotlin-Study#8]
150p에서 '자바에서는 패키지가 같은 클래스를 선언하기만 하면 어떤 프로젝트의 외부에 있는 코드라도 패키지 내부에 있는 패키지 전용 선언에 쉽게 접근할 수 있다.' 라는 문장이 있는데, 어떤 경우인지 자세히 설명 부탁드려요!

**Comment by jennkimm** [comment]
자바에서는 서로 다른 프로젝트에서 같은 이름의 패키지를 만들면, 해당 패키지에 속한 클래스(패캐지 전용 선언이 된, 또는 public)은 같은 패키지에 속한다고 간주되어 import 문 없이 접근이 가능합니다:)
[참고](https://stackoverflow.com/questions/39518235/same-package-under-different-projects)

**Comment by rosesua318** [comment]
아하 다른 프로젝트라도 같은 이름의 패키지를 만들면 import 없이 접근이 가능하다니 새로 알게 된 사실이네요 감사합니다 :)
