### ISSUE TITLE
[4.1.5 봉인된 클래스] sealed 제약

### ISSUE THREAD

**Issue by rosesua318** [jennkimm/Kotlin-Study#9]
코틀린 1.0에서는 4.1.5에서 설명한 것처럼 sealed 클래스의 모든 하위 클래스는 중첩 클래스여야 하지만, 코틀린 1.1에서는 봉인된 클래스와 같은 파일의 아무데서나 봉인된 클래스를 상속한 하위 클래스를 만들 수 있다고 되어있습니다. 그렇다면, 책에서 설명한 것과 달리, 코틀린 1.1에서는 중첩 클래스로 하위 클래스를 만드는 방법 외에 일반적인 상속인 세미콜론으로 하위 클래스 선언이 가능하다는 뜻이 맞을까요?

**Comment by jennkimm** [comment]
https://kotlinlang.org/docs/whatsnew11.html#sealed-and-data-classes 참고
